### PR TITLE
Status not translatable

### PR DESCRIPTION
**Pull request by ludmanp**

### CODE REVIEW

**Comment by sdebacker** [comment]
Hello Mark, can you describe what this pull request solves? Also I see that the code style has changed and .idea was added to the .gitignore (it's better to add .idea in your global .gitignore file).

**Comment by ludmanp** [comment]
Hello Samuel,
Sometimes I have not translatable status field for some classifiers. It can happen in both multilingual lists and not.
For that cases status button is not working, and toggleStatus works only when list is not multilingual.

**Comment by ludmanp** [comment]
Concerning .gitignore somehow phpStorm did not work properly and always wanted to push .idea folder with my changes.
Can try to make changes without php storm

**Comment by ludmanp** [comment]
.gitignore removed from pull request

**Comment by sdebacker** [comment]
Do you mean a list containing items with either a translatable or non-translatable status field?

**Comment by ludmanp** [comment]
No, I mean a list with for example translatable title and non-translatable status

**Comment by sdebacker** [comment]
That should work with TypiCMS with a proper configuration of the list. Can you give me an example of a problematic code ?

**Comment by ludmanp** [comment]
Here is a quick example https://github.com/ludmanp/typicms-status-example
Module `Locations` have status if type integer and other translatable fields
In blade `locations::admin.index` you can see that status is non-translatable, but it does not work with any `:multiligual` is `true` or `false`. 

Maybe I do something wrong, but in proper configuration `ItemList` looks to `:multilingual` property, but `ItemListStatusButton` always take `status_translated`.

**Comment by sdebacker** [comment]
Ok, I see, can you modify you PR to respect the code style of 4 spaces ? I use Prettier to format the files, see .prettierrc present in the root of typicms/base.

**Comment by ludmanp** [comment]
Fixed

**Comment by sdebacker** [comment]
Nice addition, thanks !

**Pull request merged**
